spring:
  profiles:
    active: dev




jwt:
  header: token
  expires_in: 600000 # 5 minutes
  mobile_expires_in: 600000 # 10 minutes
  secret: queenvictoria



pinduoduo:
  appId: wx32540bd863b27570
  pagePath: pages/welfare_coupon/welfare_coupon
  pid: 240009_18781180

