demo:
  service:
    version: 1.0.0

embedded:
  zookeeper:
    port: 2181
  redis:
    port: 6379

dubbo:
  protocol:
    name: dubbo
    port: -1
  #    serialization: json
  registry:
    address: zookeeper://193.112.133.54:${embedded.zookeeper.port}
    password: fulihui.com
    username: fulihui.com
  scan:
    base-packages: com.fulihui.duoduoke.demo.producer.service


  provider:
    retries: 0
    time-out: 10000


duoduoke:
  clientId: c897842201e74d47a0668b8efd0dd38e
  clientSecret: 2672db6f66cfa0d90688210f3caacad6a38de29f
  miniAppid: wxf7d16733ba8b3d65
  miniAppSecret: 2f61d1c90eebaeb8d88684a163cf0023
  mchid: 1358533402
  certFile: /home/admin/cert/apiclient_cert.p12
  authUrl: https://api.weixin.qq.com/sns/jscode2session
  templateUrl: https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token
  zkAddress: 193.112.133.54:2181
  minipage: pages/home/home
  miniProductPage: pages/product/product



spring:
  application:
    name: dubbo-registry-redis-provider
  redis:
    database: 0
    host: 192.168.1.81
    password: fulihui.com
    port: 6379
    timeout: 10000
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 10
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
  lock:
    zk:
      serverLists: 193.112.133.54:2181
server:
  port: 8081


sequence:
  workerId: 1

mybatis:
  typeAliasesPackage: com.fulihui.duoduoke.demo.producer.dal.dataobj
  mapperLocations: classpath*:sqlmap/*.xml





sharding:
  jdbc:
    datasource:
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://193.112.133.54:3306/duoduoke?characterEncoding=UTF-8
        username: root
        password: root
        initial-size: 1
        min-idle: 1
        max-active: 200
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: "SELECT 'x'"
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
      names: ds0
    config:
      sharding:
        tables:
          order_info:
            table-strategy:
              standard:
                sharding-column: custom_parameters
                precise-algorithm-class-name:  com.fulihui.duoduoke.demo.producer.biz.shard.UserIdAlgorithm
            actual-data-nodes: ds0.order_info_$->{0..9}
      props:
        sql:
          show: true

