spring:
  application:
    name: dubbo-registry-zk-job



  main:
    allow-bean-definition-overriding: true

  redis:
    database: 0
    host: 192.168.1.81
    password: fulihui.com
    port: 6379
    timeout: 10000
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 10
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1


  lock:
    zk:
      serverLists: 127.0.0.1:2181


demo:
  service:
    version: 1.0.0



logging:
  config: ./config/logback-dev.xml

aes:
  aesKey: oLhMH2xotVCzK7d8urGzeA==


embedded:
  zookeeper:
    port: 2181
  redis:
    port: 6379


regCenter:
  serverList: 127.0.0.1:2181
  namespace: com-fulihui-duoduoke-web-job-springboot



###################  web配置  ###################
web:
  mock:
    transfers: true #是否 mock 微信企业付款 (true/false)
    status: false #是否mock 微信支付成功或者失败  (true 为成功/false 失败)
  order:
    mock: false #是否mock订单拉取数据 (true/false)
    url: http://192.168.1.86:8070/duoduokemock/order/query%s





duoduoke:
  clientId: 04077b8a720947c9a33c68bbb06bae8e
  clientSecret: dc5f0dcfec0127530ee24a07c25ef8ceb129a9c1
  miniAppid: wxf7d16733ba8b3d65
  miniAppSecret: 2f61d1c90eebaeb8d88684a163cf0023
  mchid: 1358533402
  certFile: /home/admin/cert/apiclient_cert.p12
  authUrl: https://api.weixin.qq.com/sns/jscode2session
  templateUrl: https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token
  zkAddress: 127.0.0.1:2181
  minipage: pages/home/home
  miniProductPage: pages/product/product




dubbo:

  protocol:
    name: dubbo
    port: -1
  #    serialization: json
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    password: fulihui.com
    username: fulihui.com
  scan:
    base-packages: com.fulihui.duoduoke.demo.producer.job


  provider:
    retries: 0
    time-out: 10000


  consumer:
    version: 1.0.0
    check: false
    timeout: 50000
    validation: true

server:
  servlet:
    context-path: /duoduojob
  port: 8887






catGoodsJob:
  cron: 0 /1  * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
  disabled: false #false  true


orderIncrementJob:
  cron: 0 /1  * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
  disabled: true #false  true

orderDetailGetJob:
  cron: 0 */3 * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
  disabled: true #false  true

orderColorIncrementJob:
  cron: 0 */5 * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
  disabled: true









